### ISSUE TITLE
mnist_pixel missing "processed" folder

### ISSUE THREAD

**Issue by sebastiantomac** [locuslab/TCN#31]
The mnist_pixel scripts presumes that data/mnist/processed folder exists

And I also ran into the the pytorch version issue with data[0] should be data.item() or you get a IndexError: invalid index of a 0-dim tensor.

**Comment by jerrybai1995** [comment]
Hi, 

The folder was not missing; you could solve the problem by manually creating an empty one by `mkdir`. But I just fixed this problem by putting an empty folder there, so if you pull the latest version this should be fixed.

The second problem is a result of using deprecated PyTorch. I have updated the entire repo so that it's now consistent with PyTorch 1.0. Thanks for pointing this out!
