### ISSUE TITLE
Inference on Word CNN

### ISSUE THREAD

**Issue by loretoparisi** [locuslab/TCN#4]
How inference the next word / char in the word or character based TCN? Shall I use `get_batch`  like

```python
data, targets = get_batch(data_source, i, args, seq_len=1, evaluation=False)
        output = model(data)
```

Thank you.

**Comment by jerrybai1995** [comment]
You mean the case where you want to (for instance) generate the next word/character? You probably don't want to use seq_len=1, but instead an amount that is reasonable for a good history size. For instance, you can use seq_len=100, so that the previous 100 tokens will contribute to the next prediction (which is output[:,:,-1]).

Let's say you have input `x` with dimension `(N, L)` where `L=100` now. Then evaluating `model(x)` will give you an output `z` of `(N, L)` as well, where `z_i` is TCN's prediction of the next token after `x_i`. TCN's signature is very similar to that of the RNN/LSTM in PyTorch.

Hope this helps :-)

**Comment by loretoparisi** [comment]
@jerrybai1995 yes this is the case. Thanks! Regarding the words split for next token, supposed to set `seq_len=100` it means the next 100 chars i.e. it could break on a subword?

**Comment by jerrybai1995** [comment]
Setting `seq_len=100` means use (up to) the previous 100 tokens (word or char) for prediction. If you are doing character level language modeling, then yes, we could be breaking on a subword.

**Comment by loretoparisi** [comment]
@jerrybai1995 thanks ok so this means I should use the `word_cnn` rather than the `char_cnn` to avoid subwords.
